# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16e7fd40aa5cdf9e81bc75c7c0e29d0a7f2f2333a836abf7b6edf7b5f9135546981f114b942f5328ace60d9b56804736d9e01c10cd8b873cd5e756f4e808669b

test:
  secret_key_base: 6c72643496fb0bc362b3e7c3c1201bed0bcc4684cd91e250e743da535c4fe9c43e68b517b1f9732179f54e4bbfd5275ae563a529761d3e7fc2ddb4e6a5ffc1fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
