# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 006ae439fb3bf2f1b3c5085c32c8f37b081e62c28134b30cf92c513b7632b5b37b690908e17ffc3c22ed139afaa992b46ada054fc7755f48cc7aa5aacfbaccd3

test:
  secret_key_base: e7547507945e56b7fdb4ecd73e87058f2d0147694c7a4b6e57de3a8865bd50fd8a8cc988e50d053653d98183d644f4bc5e4d2c28b3353b8e6701b632ed6e306b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
