# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82f7e87a7ee2834a9c2a2db9bbcaf544d7fe8e428797f0c1aa381eac2327df55d014c7173525e3d9b50a983d0c6e47fcaecf42223eae76d3d84a1ba106722a0e

test:
  secret_key_base: dc4fdabc7653c9a163d48b86236c9fef09f04ca8f95debf750a943760ecf8513e9cdc71f80e71611222915f2f5395c34efa7c2d47bc6a18e5a71aaee65e9845a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
