# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6e6eff8f14ca4c88316dbe3a3d33ee107a9c75a8db07366525819b44870cec4ffcda74aacee126008cbe0a8593a3dc74efc8d3011d1f72e5d73a4c29790cf93

test:
  secret_key_base: a0f184792a72e5732c9d58eed23329fa0c5d70a445b3a34df41c0249fec9f1122593fb07bb1db725209a84504b660ff615f39b0053b9e59240bcd37d71652b5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
