# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ac75caaec7dc1ee1b053a384009db88b5be2a5643fccdbc4cdecd273973e1eca9b9b79a91787d6c09e20d5c71b51bc685fa916d42522926436bbe668a3cbc95

test:
  secret_key_base: a0a007f3b272a8c4392bfe3a5808495f147573efb1d179322890a82a9906dfe04b20941bef4b35096fc5a7554ea0b1d05bcd2ff106e840ed970f45a95a55993b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
